### ISSUE TITLE
What's the use of this if 75% of the mods targeted for this game is discontinued?

### ISSUE THREAD

**Issue by PF94** [fusiion/PCBSModloader#4]
Slowing down the loading times by 50%?

I'm guessing so.

**Comment by Vlad-00003** [comment]
@PF94, you are the weird one.
If you don't want to - don't use it. If you don't have any mods to use with it - just don't.

It's not like you are being forced to...

What's the use? Well. I have a set of working mods, and tbh - I'v yet to have a problems with loading times...

**Comment by PF94** [comment]
Please do not reply to this issue.
